### ISSUE TITLE
optFederov: center=TRUE error with only one numeric variable

### ISSUE THREAD

**Issue by tylermorganwall** [jvbraun/AlgDesign#3]
drop=FALSE needs to be added to the subsetting of "data" in line 40 of FederovOpt.R. Otherwise, you get the error:

> Error in apply(data[, numericColumn], 2, mean) : 
>   dim(X) must have a positive length

when the factorial design you input into optFederov only has one numeric variable.

FIX:

```
if (center) {
        means<-apply(data[,numericColumn],2,mean) #drop=FALSE needs to be added here
        data[,numericColumn]<-sweep(data[,numericColumn,drop=FALSE],2,means)
    }
```

You can recreate this with the design here:

```
factorialcoffee <- expand.grid(cost=as.numeric(c(1,2)),size=as.factor(c("Short","Grande","Venti")))
optFederov(~cost+size,data=factorialcoffee,nTrials=19,criterion = "D",nRepeats = 100,center=TRUE)
```

**Comment by jvbraun** [comment]
Thank you!  I am currently working out how to proceed with maintenance.

**Comment by tylermorganwall** [comment]
Fixed with merge, closed
